### ISSUE TITLE
Http client method `Notify` does not send the notification immediately

### ISSUE THREAD

**Issue by libreoscar** [powerman/rpc-codec#18]
Http client does not sent notification immediately. It sent a notification out when the next request is sent out via this http client. If you send only a notification over an http client, it will never really sent out.

I modified the package example for reproducing this bug.
See line 160 of https://play.golang.org/p/_uYiot-EyN

**Comment by powerman** [comment]
I believe it works as expected. Problem is, different parts doing client/server I/O runs in separate goroutines, and your main() exits earlier than these goroutines get a chance to run and do that I/O to transfer notification packet. This is because notifications are doesn't require the response and thus Notify() returns right after initiating I/O, while Call() have to wait for server's response before return. Just add `time.Sleep(time.Second)` before end of the main() to demonstrate this.
