### ISSUE TITLE
"jsonrpc":"2.0" not required in response

### ISSUE THREAD

**Issue by lfarkas** [powerman/rpc-codec#22]
hi,
according to the jsonrpc spec:
http://www.jsonrpc.org/specification#response_object
in the response the 
"jsonrpc":"2.0"
filed is NOT REQUIRED just optional. while your implementation failed if it's missing. IMHO it's a bug and would be useful to fix.
the same can be seen here:
https://en.wikipedia.org/wiki/JSON-RPC
regards.

**Comment by powerman** [comment]
I read the spec other way - to me it sounds like version field is required.
The section "3 Compatibility" says "…2.0 always has a member named "jsonrpc" with a String value of "2.0" whereas 1.0 does not…". And while description of response object doesn't include phrase "This member is REQUIRED." for version field I believe this isn't because it's optional, but because it's obvious this field is required in 2.0.

**Comment by powerman** [comment]
BTW, in case you disagree - you can ask about this in official forum https://groups.google.com/group/json-rpc to get authorized response from spec authors.
