### ISSUE TITLE
Reponse object  is not implemented correctly.

### ISSUE THREAD

**Issue by OrangeTux** [powerman/rpc-codec#5]
The response returned by this package always contains a result **and** error attribute. According to the [specification](http://www.jsonrpc.org/specification#response_object) those attributes are mutually exclusive:

> ## Response Object
> 
> ...
> 
> **result**
>     This member is REQUIRED on success.
>     This member MUST NOT exist if there was an error invoking the method.
>     The value of this member is determined by the method invoked on the Server.
> 
> **error**
>     This member is REQUIRED on error.
>     This member MUST NOT exist if there was no error triggered during invocation.
>     The value for this member MUST be an Object as defined in section 5.1.

**Comment by powerman** [comment]
Can you please provide an example? Because usually it doesn't do this:
- Server correctly defines "omitempty": https://github.com/powerman/rpc-codec/blob/master/jsonrpc2/server.go#L126
- Client correctly check received response to have either "result" or "error" but not both: https://github.com/powerman/rpc-codec/blob/master/jsonrpc2/client.go#L135
- And even tests checks for this in returned json: https://github.com/powerman/rpc-codec/blob/master/jsonrpc2/protocol_test.go#L222
